# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          # The following additional scopes may be required:
          #  - read:org      (for organization related metrics)
          #  - read:user     (for user related data)
          #  - read:packages (for some packages related data)
          #  - repo          (optional, if you want to include private repositories)
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: WhitePaper233
          languages: true
          base: header, activity, community, repositories, metadata
          base_indepth: false
          base_hireable: false
          base_skip: false
          languages_limit: 8
          languages_threshold: 0%
          languages_other: false
          languages_colors: github
          languages_sections: most-used
          languages_indepth: false
          languages_analysis_timeout: 15
          languages_categories: markup, programming
          languages_recent_categories: markup, programming
          languages_recent_load: 300
          languages_recent_days: 14
          config_timezone: Asia/Shanghai
          config_display: large